runtime: python39  # This should match your Python version
instance_class: F2  # This defines the compute resources for your instances. F2 is a class with 1.2 GB memory.
env: standard 
entrypoint: bash -c 'python manage.py migrate && gunicorn -b :$PORT toptechscore.wsgi'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  target_throughput_utilization: 0.6

env_variables:
  DJANGO_SETTINGS_MODULE: "toptechscore.settings"
  SECRET_KEY: "django-insecure-$u1a^(tm-r(!w=_@ro)#5m=+lv=e2$08!od=l#qq3sk%+p&7(w"
  DB_NAME: "postgres1"
  DB_USER: "user1"
  DB_PASSWORD: "mqy%Z9~7-Y<fsJVn"
  DB_HOST: "/cloudsql/toptechscore:us-central1:toptechscore-database"
  DB_PORT: "5432"


beta_settings:
    cloud_sql_instances: toptechscore:us-central1:toptechscore-database

