runtime: python39
instance_class: F2
env: standard 
entrypoint: bash -c 'python manage.py migrate && gunicorn -b :$PORT toptechscore.wsgi'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  target_throughput_utilization: 0.6

env_variables:
  DJANGO_SETTINGS_MODULE: "toptechscore.settings"
  SECRET_KEY: "django-insecure-$u1a^(tm-r(!w=_@ro)#5m=+lv=e2$08!od=l#qq3sk%+p&7(w"
  DB_NAME: "postgres1"
  DB_USER: "user1"
  DB_PASSWORD: "k%<]5N?7,h`JEC;I"
  DB_HOST: "/cloudsql/toptechscore:us-central1:toptechscore-database"  # Unix socket path of your Cloud SQL instance
  DB_PORT: "5432"

beta_settings:
  cloud_sql_instances: toptechscore:us-central1:toptechscore-database
  