# Generated by Django 4.2.2 on 2023-06-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AITool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("monthly_traffic", models.IntegerField()),
                ("time_spent_on_website", models.DurationField()),
            ],
        ),
    ]
