# Generated by Django 4.2.2 on 2023-06-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="aitool", name="monthly_traffic",),
        migrations.RemoveField(model_name="aitool", name="time_spent_on_website",),
        migrations.AddField(
            model_name="aitool", name="april", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="average_time_normalized",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="average_time_on_website",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="change_normalized",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aitool", name="description", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="aitool", name="engagement", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aitool", name="february", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="aitool", name="growth", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aitool", name="may", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="may_normalized",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aitool", name="popularity", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="sub_category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aitool", name="tts", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aitool", name="website", field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="aitool", name="name", field=models.CharField(max_length=255),
        ),
    ]
