# Generated by Django 4.2.2 on 2023-06-15 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0002_remove_aitool_monthly_traffic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="tts",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
