# Generated by Django 4.2.2 on 2023-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0003_alter_aitool_tts"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aitool", index=models.Index(fields=["name"], name="name_idx"),
        ),
    ]
