# Generated by Django 4.2.2 on 2023-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0004_aitool_name_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool", name="april", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="aitool", name="february", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="aitool", name="may", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="aitool", name="tts", field=models.FloatField(null=True),
        ),
    ]
