# Generated by Django 4.2.2 on 2023-06-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0007_alter_aitool_april_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="aitool", table="aitool",),
    ]
