# Generated by Django 4.2.2 on 2023-06-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0008_alter_aitool_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
