# Generated by Django 4.2.2 on 2023-06-21 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AITool",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255, null=True)),
                ("sub_category", models.CharField(max_length=255, null=True)),
                ("website", models.URLField(null=True)),
                ("description", models.TextField(null=True)),
                (
                    "february",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "april",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "may",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "average_time_on_website",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "may_normalized",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "change_normalized",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "average_time_normalized",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "tts",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "popularity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "growth",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "engagement",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "aitool",
                "indexes": [models.Index(fields=["name"], name="name_idx")],
            },
        ),
    ]
