# Generated by Django 4.2.2 on 2023-06-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="favicon_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
