# Generated by Django 4.2.2 on 2023-07-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0002_aitool_favicon_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="description_perplexity",
            field=models.TextField(blank=True, null=True),
        ),
    ]
