# Generated by Django 4.2.2 on 2023-07-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0005_alter_aitool_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="brief_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="comparison",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="problem_solution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Running"),
                            (2, "Completed"),
                            (3, "Error"),
                        ],
                        default=0,
                    ),
                ),
                ("result", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "ai_tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to="ai_tools.aitool",
                    ),
                ),
            ],
        ),
    ]
