# Generated by Django 4.2.2 on 2023-07-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0006_aitool_brief_description_aitool_comparison_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aitool", old_name="problem_solution", new_name="key_features",
        ),
    ]
