# Generated by Django 4.2.2 on 2023-07-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0007_rename_problem_solution_aitool_key_features"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aitool", old_name="feedback", new_name="pricing",
        ),
    ]
