# Generated by Django 4.2.2 on 2023-07-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0009_remove_photo_image_photo_image_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="photo", name="ai_tool",),
        migrations.AlterField(
            model_name="photo", name="image_url", field=models.URLField(),
        ),
    ]
