# Generated by Django 4.2.2 on 2023-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0012_alter_photo_image_url_delete_photourl"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urls",
                    models.TextField(help_text="Enter URLs separated by comma ','"),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="aitool", old_name="long_description", new_name="cons",
        ),
        migrations.RenameField(
            model_name="aitool", old_name="medium_description", new_name="pros",
        ),
    ]
