# Generated by Django 4.2.2 on 2023-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0013_photobatch_rename_long_description_aitool_cons_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="aitool", options={"ordering": ["-tts"]},),
        migrations.AddField(
            model_name="aitool",
            name="tts_rank",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
