# Generated by Django 4.2.2 on 2023-07-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0014_alter_aitool_options_aitool_tts_rank"),
    ]

    operations = [
        migrations.RemoveField(model_name="aitool", name="logo",),
    ]
