# Generated by Django 4.2.2 on 2023-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0016_aitool_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
